### ISSUE TITLE
Command in Installation download github HTML page

### ISSUE THREAD

**Issue by XingerTang** [AlphaGenes/AlphaPeel#10]
The command 
``
wget https://github.com/AlphaGenes/AlphaPeel/blob/master/AlphaPeel.zip
``
will download the github HTML page instead of the zip file.

To download the zip fie, we should use the URL of the raw file instead. So the command could be
``
 wget https://github.com/AlphaGenes/AlphaPeel/raw/main/AlphaPeel.zip
``

**Comment by gregorgorjanc** [comment]
Great solution @XingerTang! Can you please implement this change and request a pull? Best if you mention this issue #10 in the pull request somewhere - GitHub nicely links things up. Thanks!

**Comment by gregorgorjanc** [comment]
@XingerTang can you please check if we should move to the "raw" URL in other AlphaSuite download instructions (see projects under https://github.com/AlphaGenes - only a few will have this instruction so not many fixes needed at this stage)?

Once we have pip package (that will get uploaded to PyPi?) I guess we should remove saving wheels and the zip on GitHub, anyway, right?

**Comment by gregorgorjanc** [comment]
I reopened this issue so we don't forget fixing this;)

**Comment by XingerTang** [comment]
Other projects are either written in other languages or don't have building instructions, so the AlphaPlantImpute2 is the only one that needs to be fixed.
