### ISSUE TITLE
Rename input file arguments -pedigree, -genotypes, -seqfile, -bfile

### ISSUE THREAD

**Issue by gregorgorjanc** [AlphaGenes/AlphaPeel#109]
Rename

- [ ] `-pedigree` to `-ped_file`
- [ ] `-genotypes` to `-geno_file`
- [ ] `-seqfile` to `-seq_file`
- [ ] `-bfile` to `-plink_file`

**Comment by AprilYUZhang** [comment]
@gregorgorjanc, We have finished these changes. Could you please close this issue because I seem to have no permission to organise issues opened by others. Similar issues may be #106 #104 #102 #103 #107 #108 #110 #111.

**Comment by gregorgorjanc** [comment]
Closed as completed.
