### ISSUE TITLE
Update tests according to the changes in the options names and file names

### ISSUE THREAD

**Issue by XingerTang** [AlphaGenes/AlphaPeel#113]
@gregorgorjanc @AudreyAAMartin @AprilYUZhang

Here is a summary of the changes in the option names and the file names 

|Old option name|Updated option name|Old file name|Updated file name|Complete|Issue|
|--|--|--|--|--|--|
|-|-|dosages|dosage.txt|√|#90|
|no_dosages|no_dosage|-|-|√|#90|
|-|seg_prob|seg|seg_prob.txt|√|#96,#98|
|no_seg|-|-|-|√ |#96,#98|
|calling_threshold|geno_threshold|-|-|√ |#82|
|-|geno|called.x|geno_x.txt|√ |#82|
|-|hap_threshold|-|-|√ |#89,#82|
|call_phase|hap|called_phase.x|hap_x.txt|√ |#89,#82|
|-|geno_prob|-|geno_prob.txt|√|#93|
|haps|phased_geno_prob|haps|phased_geno_prob.txt|√|#92|
|pedigree|ped_file|INPUT FILE|INPUT FILE|√|#109|
|genotypes|geno_file|INPUT FILE|INPUT FILE|√|#109|
|seqfile|seq_file|INPUT FILE|INPUT FILE|√|#109|
|bfile|plink_file|INPUT FILE|INPUT FILE|√|#109|
|mapfile|map_file|INPUT FILE|INPUT FILE|√|#106|
|segmapfile|seg_map_file|INPUT FILE|INPUT FILE|√|#106|
|segfile|seg_file|INPUT FILE|INPUT FILE|√|#106|
|estmaf|est_alt_allele_prob|maf|alt_allele_prob.txt|√|#97,#104|
|error|geno_error_prob|-||√|#97,#102|
|seqerror|seq_error_prob|-|-|√|#97,#102|
|esterrors|est_geno_error_prob|genoError|geno_error_prob.txt|√|#97,#102,#104|
|esterrors|est_seq_error_prob|seqError|seq_error_prob.txt|√|#97,#102,#104|
|-|est_rec_prob|-|rec_prob.txt|√|#97,#104|
|length|rec_length|-|-|√|#103|
|sexchrom|sex_chrom|-|-|√|#107|
|startsnp|start_snp|-|-|√|#108|
|stopsnp|stop_snp|-|-|√|#108|
|out|out_file|-|-|√|#110|
|writekey|out_id_order|-|-|√|#110|
|onlykeyed|out_id_only|-|-|√|#110|
|iothreads|n_io_threads|-|-|√ |#110| 
|runtype|method|-|-|√|#111|
|ncycles|n_cycles|-|-|√|#111|
|maxthreads|n_threads|-|-|√|#111|

Following the naming conventions, I also suggest these changes in the names:

|Old option name|Updated option name|Old file name|Updated file name|Complete|Issue|
|--|--|--|--|--|--|
|no_params|no_param|-|-|√|#97|
|binary_call_files|binary_call_file|-|-|√|not_implemented| 
|nophasefounders|no_phase_founder|-|-|√|#112|

**Comment by gregorgorjanc** [comment]
@XingerTang I have done some edits above to fix some typos or errors. I agree with the other proposals at the top. I will now go and link all the issues together so we can track one batch of changes at a time.

**Comment by AprilYUZhang** [comment]
Here is a summary of the changes in the option names and the file names
|Old option name|Updated option name|Old file name|Updated file name|Complete|Issue|
|--|--|--|--|--|--|
|-|-|dosages|dosage.txt||#90|
|no_dosages|no_dosage|-|-|completed|#90|
|-|seg_prob|seg|seg_prob.txt||#96,#98|
|no_seg|-|-|-||#96,#98|
|calling_threshold|geno_threshold|-|-||#82|
|-|geno|called.x|geno_x.txt||#82|
|-|hap_threshold|-|-||#89,#82|
|call_phase|hap|called_phase.x|hap_x.txt||#89,#82|
|-|geno_prob|-|geno_prob.txt||#93|
|haps|phased_geno_prob|haps|phased_geno_prob.txt||#92|
|pedigree|ped_file|INPUT FILE|INPUT FILE||#109|
|genotypes|geno_file|INPUT FILE|INPUT FILE||#109|
|seqfile|seq_file|INPUT FILE|INPUT FILE||#109|
|bfile|plink_file|INPUT FILE|INPUT FILE||#109|
|mapfile|map_file|INPUT FILE|INPUT FILE||#106|
|segmapfile|seg_map_file|INPUT FILE|INPUT FILE||#106|
|segfile|seg_file|INPUT FILE|INPUT FILE||#106|
|estmaf|est_alt_allele_prob|maf|alt_allele_prob.txt||#97,#104|
|error|geno_error_prob|-|||#97,#102|
|esterrors|est_geno_error_prob|genoError|geno_error_prob.txt||#97,#102,#104|
|seqerror|seq_error_prob|-|-||#97,#102|
|esterrors|est_seq_error_prob|seqError|seq_error_prob.txt||#97,#102,#104|
|-|rec_prob|-|-||#97|
|-|est_rec_prob|-|rec_prob.txt||#97,#104|
|length|rec_length|-|-||#103|
|sexchrom|sex_chrome|-|-||#107|
|startsnp|start_snp|-|-||#108|
|stopsnp|stop_snp|-|-||#108|
|out|out_file|-|-||#110|
|writekey|out_id_order|-|-||#110|
|onlykeyed|out_id_only|-|-||#110|
|iothreads|n_io_threads|-|-||#110|
|runtype|method|-|-||#111|
|ncycles|n_cycles|-|-||#111|
|maxthreads|n_threads|-|-||#111|
Following the naming conventions, I also suggest these changes in the names:
|Old option name|Updated option name|Old file name|Updated file name|Complete|Issue|
|--|--|--|--|--|--|
|no_params|no_param|-|-||#97|
|binary_call_files|binary_call_file|-|-||not_implemented|
|nophasefounders|no_phase_founder|-|-||#112|

**Comment by AprilYUZhang** [comment]
UPDATE
Here is a summary of the changes in the option names and the file names
|Old option name|Updated option name|Old file name|Updated file name|Complete|Issue|
|--|--|--|--|--|--|
|-|-|dosages|dosage.txt|√|#90|
|no_dosages|no_dosage|-|-|√|#90|
|-|seg_prob|seg|seg_prob.txt|√|#96,#98|
|no_seg|-|-|-|√|#96,#98|
|calling_threshold|geno_threshold|-|-|√|#82|
|-|geno|called.x|geno_x.txt||#82|
|-|hap_threshold|-|-||#89,#82|
|call_phase|hap|called_phase.x|hap_x.txt|√|#89,#82|
|-|geno_prob|-|geno_prob.txt||#93|
|haps|phased_geno_prob|haps|phased_geno_prob.txt|√|#92|
|pedigree|ped_file|INPUT FILE|INPUT FILE||#109|
|genotypes|geno_file|INPUT FILE|INPUT FILE||#109|
|seqfile|seq_file|INPUT FILE|INPUT FILE||#109|
|bfile|plink_file|INPUT FILE|INPUT FILE||#109|
|mapfile|map_file|INPUT FILE|INPUT FILE||#106|
|segmapfile|seg_map_file|INPUT FILE|INPUT FILE||#106|
|segfile|seg_file|INPUT FILE|INPUT FILE||#106|
|estmaf|est_alt_allele_prob|maf|alt_allele_prob.txt||#97,#104|
|error|geno_error_prob|-|||#97,#102|
|esterrors|est_geno_error_prob|genoError|geno_error_prob.txt||#97,#102,#104|
|seqerror|seq_error_prob|-|-||#97,#102|
|esterrors|est_seq_error_prob|seqError|seq_error_prob.txt||#97,#102,#104|
|-|rec_prob|-|-||#97|
|-|est_rec_prob|-|rec_prob.txt||#97,#104|
|length|rec_length|-|-||#103|
|sexchrom|sex_chrome|-|-||#107|
|startsnp|start_snp|-|-||#108|
|stopsnp|stop_snp|-|-||#108|
|out|out_file|-|-||#110|
|writekey|out_id_order|-|-||#110|
|onlykeyed|out_id_only|-|-||#110|
|iothreads|n_io_threads|-|-||#110|
|runtype|method|-|-||#111|
|ncycles|n_cycles|-|-||#111|
|maxthreads|n_threads|-|-||#111|
|no_params|no_param|-|-||#97|
|binary_call_files|binary_call_file|-|-||not_implemented|
|nophasefounders|no_phase_founder|-|-||#112|


**Notice: all output file should be changed to .txt.**

**Comment by AprilYUZhang** [comment]
Here is a summary of the changes in the option names and the file names
|Old option name|Updated option name|Old file name|Updated file name|Complete|Issue|
|--|--|--|--|--|--|
|-|-|dosages|dosage.txt|√|#90|
|no_dosages|no_dosage|-|-|√|#90|
|-|seg_prob|seg|seg_prob.txt|√|#96,#98|
|no_seg|-|-|-|√|#96,#98|
|calling_threshold|geno_threshold|-|-|√|#82|
|-|geno|called.x|geno_x.txt|√|#82|
|-|hap_threshold|-|-||#89,#82|
|call_phase|hap|called_phase.x|hap_x.txt|√|#89,#82|
|-|geno_prob|-|geno_prob.txt||#93|
|haps|phased_geno_prob|haps|phased_geno_prob.txt|√|#92|
|pedigree|ped_file|INPUT FILE|INPUT FILE||#109|
|genotypes|geno_file|INPUT FILE|INPUT FILE||#109|
|seqfile|seq_file|INPUT FILE|INPUT FILE||#109|
|bfile|plink_file|INPUT FILE|INPUT FILE||#109|
|mapfile|map_file|INPUT FILE|INPUT FILE||#106|
|segmapfile|seg_map_file|INPUT FILE|INPUT FILE||#106|
|segfile|seg_file|INPUT FILE|INPUT FILE||#106|
|estmaf|est_alt_allele_prob|maf|alt_allele_prob.txt||#97,#104|
|error|geno_error_prob|-|||#97,#102|
|esterrors|est_geno_error_prob|genoError|geno_error_prob.txt||#97,#102,#104|
|seqerror|seq_error_prob|-|-||#97,#102|
|esterrors|est_seq_error_prob|seqError|seq_error_prob.txt||#97,#102,#104|
|-|rec_prob|-|-||#97|
|-|est_rec_prob|-|rec_prob.txt||#97,#104|
|length|rec_length|-|-||#103|
|sexchrom|sex_chrome|-|-||#107|
|startsnp|start_snp|-|-||#108|
|stopsnp|stop_snp|-|-||#108|
|out|out_file|-|-||#110|
|writekey|out_id_order|-|-||#110|
|onlykeyed|out_id_only|-|-||#110|
|iothreads|n_io_threads|-|-||#110|
|runtype|method|-|-||#111|
|ncycles|n_cycles|-|-||#111|
|maxthreads|n_threads|-|-||#111|
|no_params|no_param|-|-||#97|
|binary_call_files|binary_call_file|-|-||not_implemented|
|nophasefounders|no_phase_founder|-|-||#112|


**Notice: all output file should be changed to .txt.**

**Comment by gregorgorjanc** [comment]
@XingerTang @AprilYUZhang we should not have option `rec_prob` - this will only be an output file from `est_rec_prob` argument.

**Comment by AprilYUZhang** [comment]
I agree with you.
