### ISSUE TITLE
Adding a reference to AlphaGenes/tinyhouse 

### ISSUE THREAD

**Issue by XingerTang** [AlphaGenes/AlphaPeel#13]
As the submodule ``tinyhouse`` is used a lot in ``AlphaPeel``, I think it might be better to include a link to the project in ``README.md``.

**Comment by gregorgorjanc** [comment]
I suggest we list this as a requirement and mention that we pull in this requirement via git submodule - probably best to mention this in the installation part (as most users won't need to know this).
