### ISSUE TITLE
Help command not working

### ISSUE THREAD

**Issue by XingerTang** [AlphaGenes/AlphaPeel#14]
The command ``AlphaPeel`` works well and displays a list of arguments as expected, while ``AlphaPeel -h``  and ``AlphaPeel --help``fails.

**Comment by gregorgorjanc** [comment]
@XingerTang can you look how to expand the Python code so that `AlphaPeel -help` or `AlphaPeel -h` report the same as running just `AlphaPeel`?

**Comment by gregorgorjanc** [comment]
@XingerTang sure!
