### ISSUE TITLE
Set default hap threshold and default geno threshold

### ISSUE THREAD

**Issue by XingerTang** [AlphaGenes/AlphaPeel#146]
Fix #133 and #132

**Comment by gregorgorjanc** [comment]
@AprilYuZhang can you work on this one? We would like to use the 1/2 and 1/3 as defaults.

**Comment by AprilYUZhang** [comment]
> @AprilYUZhang can you work on this one? We would like to use the 1/2 and 1/3 as defaults.

Of course, I can. But I need some time. I am going to talk with Xinger about the problems of related arguments.

**Comment by gregorgorjanc** [comment]
@AprilYUZhang with PR https://github.com/AlphaGenes/AlphaPeel/pull/157 merged in, where do we stand with this issue?

**Comment by XingerTang** [comment]
@gregorgorjanc  This issue can be closed now.
