### ISSUE TITLE
Improve read the docs style/template

### ISSUE THREAD

**Issue by gregorgorjanc** [AlphaGenes/AlphaPeel#26]
Now that we have read the docs implemented (in https://github.com/AlphaGenes/AlphaPeel/issues/21), we should improve it to some nicer template as seen in 

https://popsim-consortium.github.io/stdpopsim-docs/stable/index.html

https://tskit.dev/msprime/docs/stable/intro.html

**Comment by XingerTang** [comment]
@gregorgorjanc [Here](https://sphinx-themes.org/) are the themes available for Sphinx.

**Comment by gregorgorjanc** [comment]
@XingerTang which is the generic one? I think this one is nice:

https://sphinx-themes.org/sample-sites/sphinx-rtd-theme/https://sphinx-themes.org/sample-sites/sphinx-rtd-theme/

How do we implement it?

**Comment by XingerTang** [comment]
@gregorgorjanc 
The default is the one we are using now. 

The theme is a third-party theme, which is published as a package. If we are rendering the webpages locally then it is enough to download the package and then modify the ``html_theme`` in ``conf.py``. But now the webpages are rendered on Read the Docs, I think what we can do is either add a ``requirement.txt`` for the documentation or [via Git or download](https://alphapeel.readthedocs.io/en/latest). I think the former is simpler to implement.

**Comment by gregorgorjanc** [comment]
@XingerTang could we add this requirement to `pyproject.toml` so we don't have some reqs in `pyproject.toml` and some in `requirement.txt` (if the latter, where should this file be?)?

We do want RtD rendering.

**Comment by XingerTang** [comment]
@gregorgorjanc 
No, we can't. ``pyproject.toml`` is for the whole repository, but the ``requirement.txt`` is only for the documentation. But I can try to add some code to ``.readthedocs.yaml`` instead and see if that works, so that we would only need ``.readthedocs.yaml`` and no other files for the documentation.

**Comment by gregorgorjanc** [comment]
@XingerTang thanks for the PR!

How does this new theme kick-in? When we will make the next publication on PyPI?

**Comment by XingerTang** [comment]
@gregorgorjanc The RtD renders a new documentation everytime a push is made, so the latest version of the documentation should already be updated with the new theme.

**Comment by gregorgorjanc** [comment]
But this has to be a tagged push, right?

Looking at https://alphapeel.readthedocs.io/en/latest/ I still see the old style - I am fine with this for now, just wonder when does the new style kick-in and how;)

**Comment by XingerTang** [comment]
@gregorgorjanc No, it doesn't have to be a tagged push. It's just that the PR hadn't merged, now it should be OK.

**Comment by gregorgorjanc** [comment]
Done! @XingerTang you are ace!
