### ISSUE TITLE
Implement black code formatting

### ISSUE THREAD

**Issue by gregorgorjanc** [AlphaGenes/AlphaPeel#36]
There is lot's of debate about code formatting, including personal styles, but with auto-formatting tools we can ignore all this.

black is one such tool for Python.

Can we implement this for our packages too? What I don't know if this is done before a commit & push or is this done on the server/GitHub side - I think it will have to be done before a commit!?

See some seetings at https://github.com/tskit-dev/tstrait/blob/main/.flake8

This will reformat all the Python code, so we should make sure we implement this and commit on code reformat as it will be impossible to spot and actual code change - all diffs will be full;)

**Comment by gregorgorjanc** [comment]
Some more neat action hooks from https://github.com/tskit-dev/tstrait/blob/main/.pre-commit-config.yaml

**Comment by gregorgorjanc** [comment]
@XingerTang should we close this issue?

**Comment by XingerTang** [comment]
@gregorgorjanc Yes!
