### ISSUE TITLE
Think of a good TOC and layout of the docs

### ISSUE THREAD

**Issue by gregorgorjanc** [AlphaGenes/AlphaPeel#39]
Current docs structure looks a bit odd - starting with dev/cont part and then intro. We should rehash this at one stage

<img width="783" alt="Screenshot 2023-07-07 at 10 30 00" src="https://github.com/AlphaGenes/AlphaPeel/assets/725834/fb95bec3-e8e9-4104-b3b1-e71cae9fb566">

**Comment by XingerTang** [comment]
@gregorgorjanc  Below is what I come up with 

```
AlphaPeel/
├─ Introduction/
│  ├─ Availability
│  ├─ Conditions of use
│  ├─ Disclaimer
├─ Getting started/
│  ├─ Install AlphaPeel (add later)
│  ├─ Graphical representation (add later)
│  ├─ An example (add later)
├─ Usage/
│  ├─ Program options
│  │  ├─ ...
│  ├─ File formats
│  │  ├─ Input file formats
│  │  │  ├─ ...
│  │  ├─ Output file formats
│  │  │  ├─ ...
├─ Contribution and Development Guide/
│  ├─ Fork the repository
│  ├─ Clone your forked repository
│  ├─ Make changes in your clone
│  ├─ Update submodules?
│  ├─ Create a pull request
│  ├─ Update the version of the package to publish the package
```

**Comment by gregorgorjanc** [comment]
@XingerTang looks great to me! It would be good to discuss this with Audrey too https://github.com/AudreyAAMartin - will ask her on Slack to weigh in here
