### ISSUE TITLE
Copy / move&link README install and build to docs

### ISSUE THREAD

**Issue by gregorgorjanc** [AlphaGenes/AlphaPeel#45]
We now have nice install and build docs in README  - should this be copied or probably best moved to the docs and we provide links in README - so that all docs are in one place and README is just a quick intro and pointers to key resources.

**Comment by gregorgorjanc** [comment]
While we will have all the GitHub actions for PyPI and RtD it is good to have full local install instructions too for developers and testers;) I used something like this just now for AlphaImpute2 (let's do all these bits for AlphaPeel and then we repeat for other tools).

```
git clone --recurse-submodules https://github.com/AlphaGenes/AlphaImpute2.git
mv AlphaImpute2 AlphaImpute2_upstream_test
cd AlphaImpute2_upstream_test
git pull
git checkout devel
git pull
python3 -m venv AlphaImpute2_env
source AlphaImpute2_env/bin/activate
python3 -m pip install --upgrade pip
python3 -m pip install --upgrade build
python3 -m build
python3 -m pip install dist/AlphaImpute2-0.0.3-py3-none-any.whl
cd example
chmod a+x run_script.sh
./run_script.sh
deactivate AlphaImpute2_env
```

**Comment by XingerTang** [comment]
@gregorgorjanc The ``AlphaPeel`` version would be something like the following
```
git clone --recurse-submodules https://github.com/AlphaGenes/AlphaPeel.git
cd AlphaPeel
python3 -m venv AlphaPeel_env
source AlphaPeel_env/bin/activate
python3 -m pip install --upgrade pip
python3 -m pip install --upgrade build
python3 -m build
python3 -m pip install dist/AlphaPeel*.whl
cd example
bash runScript.sh
deactivate AlphaPeel_env
```
But it is basically the build instructions in the README. Do we need to keep the build instructions and write a new one, or modify the build instructions to be the local install instructions?

**Comment by gregorgorjanc** [comment]
I suggest we add build instructions to dev section of the docs and link to it from the README. This way we have all this dev stuff in one place.

**Comment by XingerTang** [comment]
@gregorgorjanc I mean do we need to separate build instructions and the local install instructions you mentioned above or do we need to put them together and only write once in the documentation as they are quite similar?
