### ISSUE TITLE
@gregorgorjanc To access the version from the terminal, we can use `pip show AlphaPeel`:

### ISSUE THREAD

**Issue by jwoollia** [AlphaGenes/AlphaPeel#62]
@gregorgorjanc To access the version from the terminal, we can use `pip show AlphaPeel`:
```
(base) evie@Xingers-MacBook-Air AlphaPeel % pip show AlphaPeel 
Name: AlphaPeel
Version: 1.1.1
Summary: Multilocus and hybrid peeling
Home-page: 
Author: Andrew Whalen
Author-email: awhalen@roslin.ed.ac.uk
License: MIT license
Location: /Users/evie/mambaforge/lib/python3.10/site-packages
Requires: numba, numpy
Required-by: 
```
We can also add an option `-version` if necessary so that we can access the version of `AlphaPeel` via `AlphaPeel -version`. But for the commit hash, I am unsure if we would include the information in the software when we upload it to the PyPI.

_Originally posted by @XingerTang in https://github.com/AlphaGenes/AlphaPeel/issues/61#issuecomment-1694649335_

**Comment by jwoollia** [comment]
For example every time I open R I get the version e.g. I am on 'Beagle Scouts'.  Likewise ASReml prints the version as it runs e.g. 'AlphaPeel version 1.1.3 ...'. In Rstudio with the interface there is a help which gives the version and build. Every time I, a lazy Windows use has to go to 'terminal' or 'run' commands I worry. The latest 'brick in the wall' is I am no longer automatically an administrator due to a change in UoE policy so I then have to remember to 'Make Me An Adminstrator', but that is just another hurdle to climb over and which may appear at any time.

**Comment by gregorgorjanc** [comment]
I will close this issue since we track this one at https://github.com/AlphaGenes/AlphaPeel/issues/61, but will post the above comment from JW in there.
