### ISSUE TITLE
Inconsitent documentation of output files

### ISSUE THREAD

**Issue by Npaffen** [AlphaGenes/AlphaPeel#8]
![image](https://user-images.githubusercontent.com/57102530/213135648-b815fa26-36df-4617-94d0-d5cff7a2a743.png)

As one can see in the picture the documentation is contradictory in 4.1 Phase file. Since the explanation and the example contradict each other. Could you please state whether the decscription or the example shows the correct haplotype order?

**Comment by gregorgorjanc** [comment]
Good point @Npaffen!

Can you have a look in the code where the phase file is written out (or before that) so we can both figure out / check and fix the docs?

**Comment by gregorgorjanc** [comment]
@Npaffen this looks about right and matches all other inputs and outputs! I have fixed the typo hence closing this issue. Let us know if you spot any other inconsistencies! Thanks!
