### ISSUE TITLE
rename -no_dosages to -no_dosage

### ISSUE THREAD

**Issue by AprilYUZhang** [AlphaGenes/AlphaPeel#90]

**Comment by gregorgorjanc** [comment]
@AprilYUZhang regarding the https://github.com/AlphaGenes/AlphaPeel/commit/10143afa9aaa089b2e726cacdb5398eab39dd6a2

the change from `"-no_dosages",` to `-no_dosage",` on line 255 is good, but this likely will not be the only instance where `no_dosage` appears in the code base. Please look across all the codebase where the string `-no_dosages` appears. Hint, it will appear at least in the documentation files and elsewhere - see https://github.com/search?q=repo%3AAlphaGenes%2FAlphaPeel%20no_dosages&type=code

**Comment by AprilYUZhang** [comment]
Well, I'm not sure Why, But I don't see these "no_dosages" in my local codes, Maybe I clone a different version, so tomorrow I will ask for Evia to make sense the reason.

**Comment by AprilYUZhang** [comment]
> @AprilYUZhang as mentioned in [#91 (comment)](https://github.com/AlphaGenes/AlphaPeel/issues/91#issuecomment-1752894740), in future, please add reference to the issue number by adding the #90 into the commit message. This will link the commit to this discussion and discussion to the commit. We can then have all the discussion here in this issue instead of in the commit.

Thank you, I will add next time.

**Comment by gregorgorjanc** [comment]
This one is sorted too.
