### ISSUE TITLE
rename -haps to -phased_geno_prob

### ISSUE THREAD

**Issue by AprilYUZhang** [AlphaGenes/AlphaPeel#92]

**Comment by gregorgorjanc** [comment]
@AprilYUZhang please track these issues and once a PR is merged, please close the issue. We can always reopen it if we think that more needs to be done for a specific issue - I get a notification for the closed issues and always quickly check if we have done everything set out to do in an issue.

**Comment by AprilYUZhang** [comment]
Of course, I will check and close these issues we have solved.
